name: Build & publish Equibop (versioned)

on:
  # Runs when I create a tag like v1.2.3 (see Package & publish below)
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write   # allows creating/editing releases in THIS repo

jobs:
  release:
    # Use Windows first so NSIS installer + metadata are produced cleanly.
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3

      - name: Use Node.js 20 (pnpm cache enabled)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # IMPORTANT: tell electron-builder to publish to MY fork, without editing package.json
      - name: Create electron-builder publish override
        shell: bash
        run: |
          cat > eb.publish.yml <<'YAML'
          publish:
            - provider: github
              owner: ${GITHUB_REPOSITORY%%/*}
              repo: ${GITHUB_REPOSITORY#*/}
          YAML

      # build whatever your repo needs before packaging
      - name: Build web (optional)
        run: pnpm buildWebStandalone || echo "Skipping buildWebStandalone"
      - name: Build core (optional)
        run: pnpm buildStandalone || echo "Skipping buildStandalone"

      # --- Package & publish ---
      # electron-builder will:
      #  - create a GitHub Release for the tag (vX.Y.Z) in THIS repo
      #  - upload platform installer(s) and the updater metadata: latest.yml / latest-*.yml + blockmaps
      - name: Package & publish to GitHub Releases
        env:
          GH_TOKEN: ${{ github.token }}   # electron-builder reads GH_TOKEN
        run: |
          pnpm run package -- --publish always --config eb.publish.yml || pnpm package --publish always --config eb.publish.yml
